import * as fs from 'fs';
import * as path from 'path';
import * as https from 'https';
import { fileURLToPath } from 'url';

// Define __dirname equivalent in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function download(url: string, dest: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(dest);
    https.get(url, (response) => {
      if (response.statusCode === 301 || response.statusCode === 302) {
        // Handle redirect
        const redirectUrl = response.headers.location;
        if (redirectUrl) {
          download(redirectUrl, dest).then(resolve).catch(reject);
        } else {
          reject(new Error(`Redirect status ${response.statusCode} without location header.`));
        }
        return;
      }
      if (response.statusCode !== 200) {
        reject(new Error(`Failed to download ${url}: ${response.statusCode}`));
        return;
      }
      response.pipe(file);
      file.on('finish', () => {
        file.close();
        resolve();
      });
    }).on('error', (err) => {
      fs.unlink(dest, () => {});
      reject(err);
    });
  });
}

interface CountryCodeItem {
  name: string;
  'alpha-2': string;
  'alpha-3': string;
  'country-code': string;
  [key: string]: any;
}

async function main() {
  const publicDir = path.join(__dirname, '../../public');
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  const mapDest = path.join(publicDir, 'world-110m.json');
  console.log('Downloading world-110m.json...');
  await download('https://openlayers.org/en/latest/examples/data/topojson/world-110m.json', mapDest);
  console.log('world-110m.json downloaded successfully.');

  console.log('Downloading country codes mapping...');
  const tempCodesDest = path.join(__dirname, 'temp-codes.json');
  await download(
    'https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/slim-2/slim-2.json',
    tempCodesDest
  );

  const codesRaw = fs.readFileSync(tempCodesDest, 'utf8');
  const codesList = JSON.parse(codesRaw) as CountryCodeItem[];
  fs.unlinkSync(tempCodesDest);

  const mapping: Record<string, string> = {};
  codesList.forEach((item) => {
    const num = item['country-code'];
    const alpha2 = item['alpha-2'];
    if (num && alpha2) {
      mapping[num] = alpha2;
    }
  });

  const mappingFileDest = path.join(__dirname, '../views/AnalyticsView/countryMapping.ts');
  const content = `// Auto-generated by src/utils/download-map.ts. Do not edit directly.
export const numericToAlpha2: Record<string, string> = ${JSON.stringify(mapping, null, 2)};
`;

  fs.writeFileSync(mappingFileDest, content, 'utf8');
  console.log('countryMapping.ts generated successfully at:', mappingFileDest);
}

main().catch((err) => {
  console.error('Error running download-map.ts:', err);
  process.exit(1);
});
